# Generated by Django 5.2.7 on 2025-10-08 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=255)),
                ('work_order_no', models.CharField(max_length=255, unique=True)),
                ('work_order_date', models.DateField()),
                ('tender_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('emd_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sd_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('add_sd_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=100)),
                ('bill_date', models.DateField()),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deduction_sd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_it', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_gst2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_cess', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_royalty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_fine', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_other', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cheque_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('year', models.CharField(max_length=20)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='rws_app.work')),
            ],
        ),
    ]
