# Generated by Django 5.2.7 on 2025-10-08 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rws_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='deduction_cess',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='deduction_fine',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='deduction_gst2',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='deduction_insurance',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='deduction_it',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='deduction_other',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='deduction_royalty',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='deduction_sd',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='deduction_total',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='year',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_order_date',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_order_no',
        ),
        migrations.AddField(
            model_name='bill',
            name='cess_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Deduction: Cess'),
        ),
        migrations.AddField(
            model_name='bill',
            name='financial_year',
            field=models.CharField(blank=True, default='', help_text='e.g., 2024-25', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='fine_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Deduction: Fine'),
        ),
        migrations.AddField(
            model_name='bill',
            name='gst_2_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Deduction: GST 2%'),
        ),
        migrations.AddField(
            model_name='bill',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='GST'),
        ),
        migrations.AddField(
            model_name='bill',
            name='insurance_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Deduction: Insurance'),
        ),
        migrations.AddField(
            model_name='bill',
            name='it_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Deduction: IT'),
        ),
        migrations.AddField(
            model_name='bill',
            name='other_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Deduction: Other'),
        ),
        migrations.AddField(
            model_name='bill',
            name='royalty_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Deduction: Royalty'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sd_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Deduction: SD'),
        ),
        migrations.AddField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 8, 14, 52, 39, 894077, tzinfo=datetime.timezone.utc), verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='work_order_details',
            field=models.CharField(default=datetime.datetime(2025, 10, 8, 14, 53, 30, 388583, tzinfo=datetime.timezone.utc), max_length=255, unique=True, verbose_name='Work Order Details & Commencement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(max_length=100, verbose_name='Bill No.'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cheque_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_sd_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Additional SD'),
        ),
        migrations.AlterField(
            model_name='work',
            name='emd_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='EMD Amount'),
        ),
        migrations.AlterField(
            model_name='work',
            name='sd_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Work Order SD'),
        ),
        migrations.AlterField(
            model_name='work',
            name='tender_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_name',
            field=models.CharField(max_length=255, verbose_name='Name of Work'),
        ),
    ]
