# Generated by Django 5.2.7 on 2025-10-08 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rws_app', '0002_remove_bill_deduction_cess_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='gst_amount',
            new_name='gst',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='sd_amount',
            new_name='work_order_sd',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='cheque_amount',
        ),
        migrations.RemoveField(
            model_name='work',
            name='add_sd_amount',
        ),
        migrations.RemoveField(
            model_name='work',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_name',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_order_details',
        ),
        migrations.AddField(
            model_name='work',
            name='add_sd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Add. SD'),
        ),
        migrations.AddField(
            model_name='work',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name of Work'),
        ),
        migrations.AddField(
            model_name='work',
            name='order_details',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Work Order Date Year & Commencement'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Bill Date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(default='', max_length=100, verbose_name='Bill No.'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='financial_year',
            field=models.CharField(default='', max_length=20, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Taxable Amt'),
        ),
        migrations.AlterField(
            model_name='work',
            name='tender_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Amount of the Works to Tender'),
        ),
    ]
